-- SQL Logging Session
-- Session ID: 480353f5-27ce-4770-b09e-5dcb1d13cb12
-- Started: 2026-06-23T02:19:20.112Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_7c793b40 UNIQUEIDENTIFIER,
@Name_7c793b40 NVARCHAR(100),
@Description_7c793b40 NVARCHAR(MAX),
@Sequence_7c793b40 INT,
@IsDefault_7c793b40 BIT,
@IsTerminal_7c793b40 BIT,
@ColorCode_7c793b40 NVARCHAR(20),
@IsResolved_7c793b40 BIT
SET
  @ID_7c793b40 = 'E02A9B9E-45A0-4853-A82C-EDDC00BA5126'
SET
  @Name_7c793b40 = N'New'
SET
  @Description_7c793b40 = N'Newly reported, not yet triaged.'
SET
  @Sequence_7c793b40 = 10
SET
  @IsDefault_7c793b40 = 1
SET
  @IsTerminal_7c793b40 = 0
SET
  @ColorCode_7c793b40 = N'#EAB308'
SET
  @IsResolved_7c793b40 = 0
EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_7c793b40,
  @Name = @Name_7c793b40,
  @Description = @Description_7c793b40,
  @Sequence = @Sequence_7c793b40,
  @IsDefault = @IsDefault_7c793b40,
  @IsTerminal = @IsTerminal_7c793b40,
  @ColorCode = @ColorCode_7c793b40,
  @IsResolved = @IsResolved_7c793b40;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_4d656cb7 UNIQUEIDENTIFIER,
@Name_4d656cb7 NVARCHAR(100),
@Description_4d656cb7 NVARCHAR(MAX),
@Sequence_4d656cb7 INT,
@IsDefault_4d656cb7 BIT,
@IsTerminal_4d656cb7 BIT,
@ColorCode_4d656cb7 NVARCHAR(20),
@IsResolved_4d656cb7 BIT
SET
  @ID_4d656cb7 = '6C38314F-970D-4965-9D9E-48D6BBF690A0'
SET
  @Name_4d656cb7 = N'Triaged'
SET
  @Description_4d656cb7 = N'Reviewed and accepted; prioritized and ready to be worked.'
SET
  @Sequence_4d656cb7 = 20
SET
  @IsDefault_4d656cb7 = 0
SET
  @IsTerminal_4d656cb7 = 0
SET
  @ColorCode_4d656cb7 = N'#8B5CF6'
SET
  @IsResolved_4d656cb7 = 0
EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_4d656cb7,
  @Name = @Name_4d656cb7,
  @Description = @Description_4d656cb7,
  @Sequence = @Sequence_4d656cb7,
  @IsDefault = @IsDefault_4d656cb7,
  @IsTerminal = @IsTerminal_4d656cb7,
  @ColorCode = @ColorCode_4d656cb7,
  @IsResolved = @IsResolved_4d656cb7;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_57a061e1 UNIQUEIDENTIFIER,
@Name_57a061e1 NVARCHAR(100),
@Description_57a061e1 NVARCHAR(MAX),
@Sequence_57a061e1 INT,
@IsDefault_57a061e1 BIT,
@IsTerminal_57a061e1 BIT,
@ColorCode_57a061e1 NVARCHAR(20),
@IsResolved_57a061e1 BIT
SET
  @ID_57a061e1 = '4A9D16B2-3CFC-4E4A-A94E-B1C0D0CBFA1D'
SET
  @Name_57a061e1 = N'In Progress'
SET
  @Description_57a061e1 = N'Actively being worked on.'
SET
  @Sequence_57a061e1 = 30
SET
  @IsDefault_57a061e1 = 0
SET
  @IsTerminal_57a061e1 = 0
SET
  @ColorCode_57a061e1 = N'#3B82F6'
SET
  @IsResolved_57a061e1 = 0
EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_57a061e1,
  @Name = @Name_57a061e1,
  @Description = @Description_57a061e1,
  @Sequence = @Sequence_57a061e1,
  @IsDefault = @IsDefault_57a061e1,
  @IsTerminal = @IsTerminal_57a061e1,
  @ColorCode = @ColorCode_57a061e1,
  @IsResolved = @IsResolved_57a061e1;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_5e14f88a UNIQUEIDENTIFIER,
@Name_5e14f88a NVARCHAR(100),
@Description_5e14f88a NVARCHAR(MAX),
@Sequence_5e14f88a INT,
@IsDefault_5e14f88a BIT,
@IsTerminal_5e14f88a BIT,
@ColorCode_5e14f88a NVARCHAR(20),
@IsResolved_5e14f88a BIT
SET
  @ID_5e14f88a = '20A6DDEC-24A3-4FAD-AF5B-F291B870255D'
SET
  @Name_5e14f88a = N'Waiting on Reporter'
SET
  @Description_5e14f88a = N'Blocked pending more information or a response from the reporter.'
SET
  @Sequence_5e14f88a = 40
SET
  @IsDefault_5e14f88a = 0
SET
  @IsTerminal_5e14f88a = 0
SET
  @ColorCode_5e14f88a = N'#F97316'
SET
  @IsResolved_5e14f88a = 0
EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_5e14f88a,
  @Name = @Name_5e14f88a,
  @Description = @Description_5e14f88a,
  @Sequence = @Sequence_5e14f88a,
  @IsDefault = @IsDefault_5e14f88a,
  @IsTerminal = @IsTerminal_5e14f88a,
  @ColorCode = @ColorCode_5e14f88a,
  @IsResolved = @IsResolved_5e14f88a;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_3f66c16c UNIQUEIDENTIFIER,
@Name_3f66c16c NVARCHAR(100),
@Description_3f66c16c NVARCHAR(MAX),
@Sequence_3f66c16c INT,
@IsDefault_3f66c16c BIT,
@IsTerminal_3f66c16c BIT,
@ColorCode_3f66c16c NVARCHAR(20),
@IsResolved_3f66c16c BIT
SET
  @ID_3f66c16c = 'BA34155E-E6A5-4BAE-A57C-20BFF88275EA'
SET
  @Name_3f66c16c = N'Resolved'
SET
  @Description_3f66c16c = N'A fix or answer has been delivered; awaiting confirmation before closing.'
SET
  @Sequence_3f66c16c = 50
SET
  @IsDefault_3f66c16c = 0
SET
  @IsTerminal_3f66c16c = 0
SET
  @ColorCode_3f66c16c = N'#10B981'
SET
  @IsResolved_3f66c16c = 1
EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_3f66c16c,
  @Name = @Name_3f66c16c,
  @Description = @Description_3f66c16c,
  @Sequence = @Sequence_3f66c16c,
  @IsDefault = @IsDefault_3f66c16c,
  @IsTerminal = @IsTerminal_3f66c16c,
  @ColorCode = @ColorCode_3f66c16c,
  @IsResolved = @IsResolved_3f66c16c;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_76a4b709 UNIQUEIDENTIFIER,
@Name_76a4b709 NVARCHAR(100),
@Description_76a4b709 NVARCHAR(MAX),
@Sequence_76a4b709 INT,
@IsDefault_76a4b709 BIT,
@IsTerminal_76a4b709 BIT,
@ColorCode_76a4b709 NVARCHAR(20),
@IsResolved_76a4b709 BIT
SET
  @ID_76a4b709 = 'DC42F011-C589-41BD-8FE0-D96258245E70'
SET
  @Name_76a4b709 = N'Closed'
SET
  @Description_76a4b709 = N'Completed and confirmed. Terminal state.'
SET
  @Sequence_76a4b709 = 60
SET
  @IsDefault_76a4b709 = 0
SET
  @IsTerminal_76a4b709 = 1
SET
  @ColorCode_76a4b709 = N'#475569'
SET
  @IsResolved_76a4b709 = 0
EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_76a4b709,
  @Name = @Name_76a4b709,
  @Description = @Description_76a4b709,
  @Sequence = @Sequence_76a4b709,
  @IsDefault = @IsDefault_76a4b709,
  @IsTerminal = @IsTerminal_76a4b709,
  @ColorCode = @ColorCode_76a4b709,
  @IsResolved = @IsResolved_76a4b709;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_2b34ba9a UNIQUEIDENTIFIER,
@Name_2b34ba9a NVARCHAR(100),
@Description_2b34ba9a NVARCHAR(MAX),
@Sequence_2b34ba9a INT,
@IsDefault_2b34ba9a BIT,
@IsTerminal_2b34ba9a BIT,
@ColorCode_2b34ba9a NVARCHAR(20),
@IsResolved_2b34ba9a BIT
SET
  @ID_2b34ba9a = '7B4A372A-E9F9-4685-A093-9D69C3D892C2'
SET
  @Name_2b34ba9a = N'Won''t Fix'
SET
  @Description_2b34ba9a = N'Acknowledged but will not be addressed (by design, duplicate, or out of scope). Terminal state.'
SET
  @Sequence_2b34ba9a = 70
SET
  @IsDefault_2b34ba9a = 0
SET
  @IsTerminal_2b34ba9a = 1
SET
  @ColorCode_2b34ba9a = N'#9CA3AF'
SET
  @IsResolved_2b34ba9a = 0
EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_2b34ba9a,
  @Name = @Name_2b34ba9a,
  @Description = @Description_2b34ba9a,
  @Sequence = @Sequence_2b34ba9a,
  @IsDefault = @IsDefault_2b34ba9a,
  @IsTerminal = @IsTerminal_2b34ba9a,
  @ColorCode = @ColorCode_2b34ba9a,
  @IsResolved = @IsResolved_2b34ba9a;

GO

-- Save MJ_BizApps_Issues: Issue Types (core SP call only)
DECLARE @ID_82366ff6 UNIQUEIDENTIFIER,
@Name_82366ff6 NVARCHAR(100),
@Description_82366ff6 NVARCHAR(MAX),
@IconClass_82366ff6 NVARCHAR(100),
@DefaultPriority_82366ff6 NVARCHAR(20),
@DefaultTaskTypeID_82366ff6 UNIQUEIDENTIFIER,
@OnCreateActionID_82366ff6 UNIQUEIDENTIFIER,
@OnStatusChangeActionID_82366ff6 UNIQUEIDENTIFIER,
@OnAssignActionID_82366ff6 UNIQUEIDENTIFIER,
@OnCloseActionID_82366ff6 UNIQUEIDENTIFIER,
@IsActive_82366ff6 BIT
SET
  @ID_82366ff6 = 'A4A4B67C-DEFF-4CA0-9F3C-2467CB2D2D8D'
SET
  @Name_82366ff6 = N'Bug'
SET
  @Description_82366ff6 = N'Something is broken or not behaving as intended.'
SET
  @IconClass_82366ff6 = N'fa-solid fa-bug'
SET
  @DefaultPriority_82366ff6 = N'High'
SET
  @IsActive_82366ff6 = 1
EXEC [__mj_BizAppsIssues].spCreateIssueType @ID = @ID_82366ff6,
  @Name = @Name_82366ff6,
  @Description = @Description_82366ff6,
  @IconClass = @IconClass_82366ff6,
  @DefaultPriority = @DefaultPriority_82366ff6,
  @DefaultTaskTypeID = @DefaultTaskTypeID_82366ff6,
  @DefaultTaskTypeID_Clear = 1,
  @OnCreateActionID = @OnCreateActionID_82366ff6,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_82366ff6,
  @OnStatusChangeActionID_Clear = 1,
  @OnAssignActionID = @OnAssignActionID_82366ff6,
  @OnAssignActionID_Clear = 1,
  @OnCloseActionID = @OnCloseActionID_82366ff6,
  @OnCloseActionID_Clear = 1,
  @IsActive = @IsActive_82366ff6;

GO

-- Save MJ_BizApps_Issues: Issue Types (core SP call only)
DECLARE @ID_594d9353 UNIQUEIDENTIFIER,
@Name_594d9353 NVARCHAR(100),
@Description_594d9353 NVARCHAR(MAX),
@IconClass_594d9353 NVARCHAR(100),
@DefaultPriority_594d9353 NVARCHAR(20),
@DefaultTaskTypeID_594d9353 UNIQUEIDENTIFIER,
@OnCreateActionID_594d9353 UNIQUEIDENTIFIER,
@OnStatusChangeActionID_594d9353 UNIQUEIDENTIFIER,
@OnAssignActionID_594d9353 UNIQUEIDENTIFIER,
@OnCloseActionID_594d9353 UNIQUEIDENTIFIER,
@IsActive_594d9353 BIT
SET
  @ID_594d9353 = '34733CAF-A7C4-4AF1-A6B6-7F082192E53F'
SET
  @Name_594d9353 = N'Feature Request'
SET
  @Description_594d9353 = N'A request for new functionality or an enhancement.'
SET
  @IconClass_594d9353 = N'fa-solid fa-lightbulb'
SET
  @DefaultPriority_594d9353 = N'Medium'
SET
  @IsActive_594d9353 = 1
EXEC [__mj_BizAppsIssues].spCreateIssueType @ID = @ID_594d9353,
  @Name = @Name_594d9353,
  @Description = @Description_594d9353,
  @IconClass = @IconClass_594d9353,
  @DefaultPriority = @DefaultPriority_594d9353,
  @DefaultTaskTypeID = @DefaultTaskTypeID_594d9353,
  @DefaultTaskTypeID_Clear = 1,
  @OnCreateActionID = @OnCreateActionID_594d9353,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_594d9353,
  @OnStatusChangeActionID_Clear = 1,
  @OnAssignActionID = @OnAssignActionID_594d9353,
  @OnAssignActionID_Clear = 1,
  @OnCloseActionID = @OnCloseActionID_594d9353,
  @OnCloseActionID_Clear = 1,
  @IsActive = @IsActive_594d9353;

GO

-- Save MJ_BizApps_Issues: Issue Types (core SP call only)
DECLARE @ID_7cd89b91 UNIQUEIDENTIFIER,
@Name_7cd89b91 NVARCHAR(100),
@Description_7cd89b91 NVARCHAR(MAX),
@IconClass_7cd89b91 NVARCHAR(100),
@DefaultPriority_7cd89b91 NVARCHAR(20),
@DefaultTaskTypeID_7cd89b91 UNIQUEIDENTIFIER,
@OnCreateActionID_7cd89b91 UNIQUEIDENTIFIER,
@OnStatusChangeActionID_7cd89b91 UNIQUEIDENTIFIER,
@OnAssignActionID_7cd89b91 UNIQUEIDENTIFIER,
@OnCloseActionID_7cd89b91 UNIQUEIDENTIFIER,
@IsActive_7cd89b91 BIT
SET
  @ID_7cd89b91 = '5D6CE5C4-DFA7-452B-BDCD-0E5456C683B3'
SET
  @Name_7cd89b91 = N'Question'
SET
  @Description_7cd89b91 = N'A question or request for help; no code change necessarily implied.'
SET
  @IconClass_7cd89b91 = N'fa-solid fa-circle-question'
SET
  @DefaultPriority_7cd89b91 = N'Low'
SET
  @IsActive_7cd89b91 = 1
EXEC [__mj_BizAppsIssues].spCreateIssueType @ID = @ID_7cd89b91,
  @Name = @Name_7cd89b91,
  @Description = @Description_7cd89b91,
  @IconClass = @IconClass_7cd89b91,
  @DefaultPriority = @DefaultPriority_7cd89b91,
  @DefaultTaskTypeID = @DefaultTaskTypeID_7cd89b91,
  @DefaultTaskTypeID_Clear = 1,
  @OnCreateActionID = @OnCreateActionID_7cd89b91,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_7cd89b91,
  @OnStatusChangeActionID_Clear = 1,
  @OnAssignActionID = @OnAssignActionID_7cd89b91,
  @OnAssignActionID_Clear = 1,
  @OnCloseActionID = @OnCloseActionID_7cd89b91,
  @OnCloseActionID_Clear = 1,
  @IsActive = @IsActive_7cd89b91;

GO

-- Save MJ_BizApps_Issues: Issue Types (core SP call only)
DECLARE @ID_cf8c3b60 UNIQUEIDENTIFIER,
@Name_cf8c3b60 NVARCHAR(100),
@Description_cf8c3b60 NVARCHAR(MAX),
@IconClass_cf8c3b60 NVARCHAR(100),
@DefaultPriority_cf8c3b60 NVARCHAR(20),
@DefaultTaskTypeID_cf8c3b60 UNIQUEIDENTIFIER,
@OnCreateActionID_cf8c3b60 UNIQUEIDENTIFIER,
@OnStatusChangeActionID_cf8c3b60 UNIQUEIDENTIFIER,
@OnAssignActionID_cf8c3b60 UNIQUEIDENTIFIER,
@OnCloseActionID_cf8c3b60 UNIQUEIDENTIFIER,
@IsActive_cf8c3b60 BIT
SET
  @ID_cf8c3b60 = 'FE0C6A23-ACF0-4826-BB07-1640767874C3'
SET
  @Name_cf8c3b60 = N'Feedback'
SET
  @Description_cf8c3b60 = N'General feedback or a suggestion, e.g. from the cloud feedback channel.'
SET
  @IconClass_cf8c3b60 = N'fa-solid fa-comment-dots'
SET
  @DefaultPriority_cf8c3b60 = N'Medium'
SET
  @IsActive_cf8c3b60 = 1
EXEC [__mj_BizAppsIssues].spCreateIssueType @ID = @ID_cf8c3b60,
  @Name = @Name_cf8c3b60,
  @Description = @Description_cf8c3b60,
  @IconClass = @IconClass_cf8c3b60,
  @DefaultPriority = @DefaultPriority_cf8c3b60,
  @DefaultTaskTypeID = @DefaultTaskTypeID_cf8c3b60,
  @DefaultTaskTypeID_Clear = 1,
  @OnCreateActionID = @OnCreateActionID_cf8c3b60,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_cf8c3b60,
  @OnStatusChangeActionID_Clear = 1,
  @OnAssignActionID = @OnAssignActionID_cf8c3b60,
  @OnAssignActionID_Clear = 1,
  @OnCloseActionID = @OnCloseActionID_cf8c3b60,
  @OnCloseActionID_Clear = 1,
  @IsActive = @IsActive_cf8c3b60;

GO


-- End of SQL Logging Session
-- Session ID: 480353f5-27ce-4770-b09e-5dcb1d13cb12
-- Completed: 2026-06-23T02:19:20.576Z
-- Duration: 464ms
-- Total Statements: 11
