-- SQL Logging Session
-- Session ID: 0dff1d8b-772b-4c2f-9b0a-761563ea7c88
-- Started: 2026-06-11T18:18:07.299Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_b6740769 UNIQUEIDENTIFIER,
@Name_b6740769 NVARCHAR(100),
@Description_b6740769 NVARCHAR(MAX),
@Sequence_b6740769 INT,
@IsDefault_b6740769 BIT,
@IsTerminal_b6740769 BIT,
@ColorCode_b6740769 NVARCHAR(20)
SET
  @ID_b6740769 = 'E02A9B9E-45A0-4853-A82C-EDDC00BA5126'
SET
  @Name_b6740769 = N'New'
SET
  @Description_b6740769 = N'Newly reported, not yet triaged.'
SET
  @Sequence_b6740769 = 10
SET
  @IsDefault_b6740769 = 1
SET
  @IsTerminal_b6740769 = 0
SET
  @ColorCode_b6740769 = N'#6B7280' EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_b6740769,
  @Name = @Name_b6740769,
  @Description = @Description_b6740769,
  @Sequence = @Sequence_b6740769,
  @IsDefault = @IsDefault_b6740769,
  @IsTerminal = @IsTerminal_b6740769,
  @ColorCode = @ColorCode_b6740769;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_509f8a08 UNIQUEIDENTIFIER,
@Name_509f8a08 NVARCHAR(100),
@Description_509f8a08 NVARCHAR(MAX),
@Sequence_509f8a08 INT,
@IsDefault_509f8a08 BIT,
@IsTerminal_509f8a08 BIT,
@ColorCode_509f8a08 NVARCHAR(20)
SET
  @ID_509f8a08 = '6C38314F-970D-4965-9D9E-48D6BBF690A0'
SET
  @Name_509f8a08 = N'Triaged'
SET
  @Description_509f8a08 = N'Reviewed and accepted; prioritized and ready to be worked.'
SET
  @Sequence_509f8a08 = 20
SET
  @IsDefault_509f8a08 = 0
SET
  @IsTerminal_509f8a08 = 0
SET
  @ColorCode_509f8a08 = N'#3B82F6' EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_509f8a08,
  @Name = @Name_509f8a08,
  @Description = @Description_509f8a08,
  @Sequence = @Sequence_509f8a08,
  @IsDefault = @IsDefault_509f8a08,
  @IsTerminal = @IsTerminal_509f8a08,
  @ColorCode = @ColorCode_509f8a08;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_8b7a4208 UNIQUEIDENTIFIER,
@Name_8b7a4208 NVARCHAR(100),
@Description_8b7a4208 NVARCHAR(MAX),
@Sequence_8b7a4208 INT,
@IsDefault_8b7a4208 BIT,
@IsTerminal_8b7a4208 BIT,
@ColorCode_8b7a4208 NVARCHAR(20)
SET
  @ID_8b7a4208 = '4A9D16B2-3CFC-4E4A-A94E-B1C0D0CBFA1D'
SET
  @Name_8b7a4208 = N'In Progress'
SET
  @Description_8b7a4208 = N'Actively being worked on.'
SET
  @Sequence_8b7a4208 = 30
SET
  @IsDefault_8b7a4208 = 0
SET
  @IsTerminal_8b7a4208 = 0
SET
  @ColorCode_8b7a4208 = N'#F59E0B' EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_8b7a4208,
  @Name = @Name_8b7a4208,
  @Description = @Description_8b7a4208,
  @Sequence = @Sequence_8b7a4208,
  @IsDefault = @IsDefault_8b7a4208,
  @IsTerminal = @IsTerminal_8b7a4208,
  @ColorCode = @ColorCode_8b7a4208;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_e9ee7f36 UNIQUEIDENTIFIER,
@Name_e9ee7f36 NVARCHAR(100),
@Description_e9ee7f36 NVARCHAR(MAX),
@Sequence_e9ee7f36 INT,
@IsDefault_e9ee7f36 BIT,
@IsTerminal_e9ee7f36 BIT,
@ColorCode_e9ee7f36 NVARCHAR(20)
SET
  @ID_e9ee7f36 = '20A6DDEC-24A3-4FAD-AF5B-F291B870255D'
SET
  @Name_e9ee7f36 = N'Waiting on Reporter'
SET
  @Description_e9ee7f36 = N'Blocked pending more information or a response from the reporter.'
SET
  @Sequence_e9ee7f36 = 40
SET
  @IsDefault_e9ee7f36 = 0
SET
  @IsTerminal_e9ee7f36 = 0
SET
  @ColorCode_e9ee7f36 = N'#A855F7' EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_e9ee7f36,
  @Name = @Name_e9ee7f36,
  @Description = @Description_e9ee7f36,
  @Sequence = @Sequence_e9ee7f36,
  @IsDefault = @IsDefault_e9ee7f36,
  @IsTerminal = @IsTerminal_e9ee7f36,
  @ColorCode = @ColorCode_e9ee7f36;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_346753ab UNIQUEIDENTIFIER,
@Name_346753ab NVARCHAR(100),
@Description_346753ab NVARCHAR(MAX),
@Sequence_346753ab INT,
@IsDefault_346753ab BIT,
@IsTerminal_346753ab BIT,
@ColorCode_346753ab NVARCHAR(20)
SET
  @ID_346753ab = 'BA34155E-E6A5-4BAE-A57C-20BFF88275EA'
SET
  @Name_346753ab = N'Resolved'
SET
  @Description_346753ab = N'A fix or answer has been delivered; awaiting confirmation before closing.'
SET
  @Sequence_346753ab = 50
SET
  @IsDefault_346753ab = 0
SET
  @IsTerminal_346753ab = 0
SET
  @ColorCode_346753ab = N'#10B981' EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_346753ab,
  @Name = @Name_346753ab,
  @Description = @Description_346753ab,
  @Sequence = @Sequence_346753ab,
  @IsDefault = @IsDefault_346753ab,
  @IsTerminal = @IsTerminal_346753ab,
  @ColorCode = @ColorCode_346753ab;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_5d7d7187 UNIQUEIDENTIFIER,
@Name_5d7d7187 NVARCHAR(100),
@Description_5d7d7187 NVARCHAR(MAX),
@Sequence_5d7d7187 INT,
@IsDefault_5d7d7187 BIT,
@IsTerminal_5d7d7187 BIT,
@ColorCode_5d7d7187 NVARCHAR(20)
SET
  @ID_5d7d7187 = 'DC42F011-C589-41BD-8FE0-D96258245E70'
SET
  @Name_5d7d7187 = N'Closed'
SET
  @Description_5d7d7187 = N'Completed and confirmed. Terminal state.'
SET
  @Sequence_5d7d7187 = 60
SET
  @IsDefault_5d7d7187 = 0
SET
  @IsTerminal_5d7d7187 = 1
SET
  @ColorCode_5d7d7187 = N'#374151' EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_5d7d7187,
  @Name = @Name_5d7d7187,
  @Description = @Description_5d7d7187,
  @Sequence = @Sequence_5d7d7187,
  @IsDefault = @IsDefault_5d7d7187,
  @IsTerminal = @IsTerminal_5d7d7187,
  @ColorCode = @ColorCode_5d7d7187;

GO

-- Save MJ_BizApps_Issues: Issue Status (core SP call only)
DECLARE @ID_da0cdde6 UNIQUEIDENTIFIER,
@Name_da0cdde6 NVARCHAR(100),
@Description_da0cdde6 NVARCHAR(MAX),
@Sequence_da0cdde6 INT,
@IsDefault_da0cdde6 BIT,
@IsTerminal_da0cdde6 BIT,
@ColorCode_da0cdde6 NVARCHAR(20)
SET
  @ID_da0cdde6 = '7B4A372A-E9F9-4685-A093-9D69C3D892C2'
SET
  @Name_da0cdde6 = N'Won''t Fix'
SET
  @Description_da0cdde6 = N'Acknowledged but will not be addressed (by design, duplicate, or out of scope). Terminal state.'
SET
  @Sequence_da0cdde6 = 70
SET
  @IsDefault_da0cdde6 = 0
SET
  @IsTerminal_da0cdde6 = 1
SET
  @ColorCode_da0cdde6 = N'#9CA3AF' EXEC [__mj_BizAppsIssues].spCreateIssueStatus @ID = @ID_da0cdde6,
  @Name = @Name_da0cdde6,
  @Description = @Description_da0cdde6,
  @Sequence = @Sequence_da0cdde6,
  @IsDefault = @IsDefault_da0cdde6,
  @IsTerminal = @IsTerminal_da0cdde6,
  @ColorCode = @ColorCode_da0cdde6;

GO

-- Save MJ_BizApps_Issues: Issue Types (core SP call only)
DECLARE @ID_8758b0cd UNIQUEIDENTIFIER,
@Name_8758b0cd NVARCHAR(100),
@Description_8758b0cd NVARCHAR(MAX),
@IconClass_8758b0cd NVARCHAR(100),
@DefaultPriority_8758b0cd NVARCHAR(20),
@DefaultTaskTypeID_8758b0cd UNIQUEIDENTIFIER,
@OnCreateActionID_8758b0cd UNIQUEIDENTIFIER,
@OnStatusChangeActionID_8758b0cd UNIQUEIDENTIFIER,
@OnAssignActionID_8758b0cd UNIQUEIDENTIFIER,
@OnCloseActionID_8758b0cd UNIQUEIDENTIFIER,
@IsActive_8758b0cd BIT
SET
  @ID_8758b0cd = 'A4A4B67C-DEFF-4CA0-9F3C-2467CB2D2D8D'
SET
  @Name_8758b0cd = N'Bug'
SET
  @Description_8758b0cd = N'Something is broken or not behaving as intended.'
SET
  @IconClass_8758b0cd = N'fa-solid fa-bug'
SET
  @DefaultPriority_8758b0cd = N'High'
SET
  @IsActive_8758b0cd = 1
EXEC [__mj_BizAppsIssues].spCreateIssueType @ID = @ID_8758b0cd,
  @Name = @Name_8758b0cd,
  @Description = @Description_8758b0cd,
  @IconClass = @IconClass_8758b0cd,
  @DefaultPriority = @DefaultPriority_8758b0cd,
  @DefaultTaskTypeID = @DefaultTaskTypeID_8758b0cd,
  @DefaultTaskTypeID_Clear = 1,
  @OnCreateActionID = @OnCreateActionID_8758b0cd,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_8758b0cd,
  @OnStatusChangeActionID_Clear = 1,
  @OnAssignActionID = @OnAssignActionID_8758b0cd,
  @OnAssignActionID_Clear = 1,
  @OnCloseActionID = @OnCloseActionID_8758b0cd,
  @OnCloseActionID_Clear = 1,
  @IsActive = @IsActive_8758b0cd;

GO

-- Save MJ_BizApps_Issues: Issue Types (core SP call only)
DECLARE @ID_7efeaec2 UNIQUEIDENTIFIER,
@Name_7efeaec2 NVARCHAR(100),
@Description_7efeaec2 NVARCHAR(MAX),
@IconClass_7efeaec2 NVARCHAR(100),
@DefaultPriority_7efeaec2 NVARCHAR(20),
@DefaultTaskTypeID_7efeaec2 UNIQUEIDENTIFIER,
@OnCreateActionID_7efeaec2 UNIQUEIDENTIFIER,
@OnStatusChangeActionID_7efeaec2 UNIQUEIDENTIFIER,
@OnAssignActionID_7efeaec2 UNIQUEIDENTIFIER,
@OnCloseActionID_7efeaec2 UNIQUEIDENTIFIER,
@IsActive_7efeaec2 BIT
SET
  @ID_7efeaec2 = '34733CAF-A7C4-4AF1-A6B6-7F082192E53F'
SET
  @Name_7efeaec2 = N'Feature Request'
SET
  @Description_7efeaec2 = N'A request for new functionality or an enhancement.'
SET
  @IconClass_7efeaec2 = N'fa-solid fa-lightbulb'
SET
  @DefaultPriority_7efeaec2 = N'Medium'
SET
  @IsActive_7efeaec2 = 1
EXEC [__mj_BizAppsIssues].spCreateIssueType @ID = @ID_7efeaec2,
  @Name = @Name_7efeaec2,
  @Description = @Description_7efeaec2,
  @IconClass = @IconClass_7efeaec2,
  @DefaultPriority = @DefaultPriority_7efeaec2,
  @DefaultTaskTypeID = @DefaultTaskTypeID_7efeaec2,
  @DefaultTaskTypeID_Clear = 1,
  @OnCreateActionID = @OnCreateActionID_7efeaec2,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_7efeaec2,
  @OnStatusChangeActionID_Clear = 1,
  @OnAssignActionID = @OnAssignActionID_7efeaec2,
  @OnAssignActionID_Clear = 1,
  @OnCloseActionID = @OnCloseActionID_7efeaec2,
  @OnCloseActionID_Clear = 1,
  @IsActive = @IsActive_7efeaec2;

GO

-- Save MJ_BizApps_Issues: Issue Types (core SP call only)
DECLARE @ID_6f77e42d UNIQUEIDENTIFIER,
@Name_6f77e42d NVARCHAR(100),
@Description_6f77e42d NVARCHAR(MAX),
@IconClass_6f77e42d NVARCHAR(100),
@DefaultPriority_6f77e42d NVARCHAR(20),
@DefaultTaskTypeID_6f77e42d UNIQUEIDENTIFIER,
@OnCreateActionID_6f77e42d UNIQUEIDENTIFIER,
@OnStatusChangeActionID_6f77e42d UNIQUEIDENTIFIER,
@OnAssignActionID_6f77e42d UNIQUEIDENTIFIER,
@OnCloseActionID_6f77e42d UNIQUEIDENTIFIER,
@IsActive_6f77e42d BIT
SET
  @ID_6f77e42d = '5D6CE5C4-DFA7-452B-BDCD-0E5456C683B3'
SET
  @Name_6f77e42d = N'Question'
SET
  @Description_6f77e42d = N'A question or request for help; no code change necessarily implied.'
SET
  @IconClass_6f77e42d = N'fa-solid fa-circle-question'
SET
  @DefaultPriority_6f77e42d = N'Low'
SET
  @IsActive_6f77e42d = 1
EXEC [__mj_BizAppsIssues].spCreateIssueType @ID = @ID_6f77e42d,
  @Name = @Name_6f77e42d,
  @Description = @Description_6f77e42d,
  @IconClass = @IconClass_6f77e42d,
  @DefaultPriority = @DefaultPriority_6f77e42d,
  @DefaultTaskTypeID = @DefaultTaskTypeID_6f77e42d,
  @DefaultTaskTypeID_Clear = 1,
  @OnCreateActionID = @OnCreateActionID_6f77e42d,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_6f77e42d,
  @OnStatusChangeActionID_Clear = 1,
  @OnAssignActionID = @OnAssignActionID_6f77e42d,
  @OnAssignActionID_Clear = 1,
  @OnCloseActionID = @OnCloseActionID_6f77e42d,
  @OnCloseActionID_Clear = 1,
  @IsActive = @IsActive_6f77e42d;

GO

-- Save MJ_BizApps_Issues: Issue Types (core SP call only)
DECLARE @ID_7312b36a UNIQUEIDENTIFIER,
@Name_7312b36a NVARCHAR(100),
@Description_7312b36a NVARCHAR(MAX),
@IconClass_7312b36a NVARCHAR(100),
@DefaultPriority_7312b36a NVARCHAR(20),
@DefaultTaskTypeID_7312b36a UNIQUEIDENTIFIER,
@OnCreateActionID_7312b36a UNIQUEIDENTIFIER,
@OnStatusChangeActionID_7312b36a UNIQUEIDENTIFIER,
@OnAssignActionID_7312b36a UNIQUEIDENTIFIER,
@OnCloseActionID_7312b36a UNIQUEIDENTIFIER,
@IsActive_7312b36a BIT
SET
  @ID_7312b36a = 'FE0C6A23-ACF0-4826-BB07-1640767874C3'
SET
  @Name_7312b36a = N'Feedback'
SET
  @Description_7312b36a = N'General feedback or a suggestion, e.g. from the cloud feedback channel.'
SET
  @IconClass_7312b36a = N'fa-solid fa-comment-dots'
SET
  @DefaultPriority_7312b36a = N'Medium'
SET
  @IsActive_7312b36a = 1
EXEC [__mj_BizAppsIssues].spCreateIssueType @ID = @ID_7312b36a,
  @Name = @Name_7312b36a,
  @Description = @Description_7312b36a,
  @IconClass = @IconClass_7312b36a,
  @DefaultPriority = @DefaultPriority_7312b36a,
  @DefaultTaskTypeID = @DefaultTaskTypeID_7312b36a,
  @DefaultTaskTypeID_Clear = 1,
  @OnCreateActionID = @OnCreateActionID_7312b36a,
  @OnCreateActionID_Clear = 1,
  @OnStatusChangeActionID = @OnStatusChangeActionID_7312b36a,
  @OnStatusChangeActionID_Clear = 1,
  @OnAssignActionID = @OnAssignActionID_7312b36a,
  @OnAssignActionID_Clear = 1,
  @OnCloseActionID = @OnCloseActionID_7312b36a,
  @OnCloseActionID_Clear = 1,
  @IsActive = @IsActive_7312b36a;

GO


-- End of SQL Logging Session
-- Session ID: 0dff1d8b-772b-4c2f-9b0a-761563ea7c88
-- Completed: 2026-06-11T18:18:07.809Z
-- Duration: 510ms
-- Total Statements: 11
