-- =============================================================================
-- Metadata Sync — v1.2.x release
-- =============================================================================
--
-- Generated by `mj sync push` against a clean database built from MJ core,
-- bizapps-common (through V202608262255), bizapps-tasks (through
-- V202608270002), and every bizapps-issues migration through V202606221300,
-- per the release-time metadata sync ritual (see V202606221300 for the v1.0.x
-- run and bizapps-common's V202608140800 for the documented corrections).
-- This file is the emitted metadata/sql_logging output with the standard
-- corrections applied:
--
--   * Core SP calls (spCreateApplication, spCreateApplicationRole,
--     spUpdateEntity, spUpdateEntityRelationship) reference ${mjSchema} —
--     they exist only in __mj, and `mj migrate --schema __mj_BizAppsIssues`
--     binds flyway:defaultSchema to THIS app's schema.
--   * Two `spCreateUserApplication` calls were removed: they bind the
--     Application to the pushing developer's own User row, which is
--     machine-specific. No prior Metadata_Sync migration ships them.
--
-- WHAT THIS CARRIES — the delta between metadata/ (source of truth) and a
-- database built purely from migrations:
--   * MJ: Applications — the Issues application record (metadata/applications/)
--   * MJ: Application Roles — 2 records wiring the Issues application's roles
--   * MJ: Entities — 1 update (form configuration from metadata/entities/)
--   * MJ: Entity Relationships — 4 updates (form-chrome placement from
--     metadata/entity-relationships/)
-- =============================================================================

-- Save MJ: Applications (core SP call only)
DECLARE @ID_3bd750a6 UNIQUEIDENTIFIER,
@Name_3bd750a6 NVARCHAR(100),
@Description_3bd750a6 NVARCHAR(MAX),
@Icon_3bd750a6 NVARCHAR(500),
@DefaultForNewUser_3bd750a6 BIT,
@SchemaAutoAddNewEntities_3bd750a6 NVARCHAR(MAX),
@Color_3bd750a6 NVARCHAR(20),
@DefaultNavItems_3bd750a6 NVARCHAR(MAX),
@ClassName_3bd750a6 NVARCHAR(255),
@DefaultSequence_3bd750a6 INT,
@Status_3bd750a6 NVARCHAR(20),
@NavigationStyle_3bd750a6 NVARCHAR(20),
@TopNavLocation_3bd750a6 NVARCHAR(30),
@HideNavBarIconWhenActive_3bd750a6 BIT,
@Path_3bd750a6 NVARCHAR(100),
@AutoUpdatePath_3bd750a6 BIT,
@AgentSettings_3bd750a6 NVARCHAR(MAX)
SET
  @ID_3bd750a6 = '1D63E8A6-BFFA-4EA7-8231-7565CABBE53E'
SET
  @Name_3bd750a6 = N'Issues'
SET
  @Description_3bd750a6 = N'Issue tracking, defect triage, Kanban resolution boards, SLA monitoring, and customer feedback management across MemberJunction.'
SET
  @Icon_3bd750a6 = N'fa-solid fa-bug'
SET
  @DefaultForNewUser_3bd750a6 = 1
SET
  @DefaultNavItems_3bd750a6 = N'[
  {
    "Label": "Issues",
    "Icon": "fa-solid fa-bug",
    "ResourceType": "Custom",
    "DriverClass": "IssuesSectionResource",
    "isDefault": true
  },
  {
    "Label": "My Issues",
    "Icon": "fa-solid fa-user-shield",
    "ResourceType": "Custom",
    "DriverClass": "MyIssuesSectionResource",
    "isDefault": false
  },
  {
    "Label": "Triage & SLAs",
    "Icon": "fa-solid fa-stopwatch-20",
    "ResourceType": "Custom",
    "DriverClass": "IssueTriageSectionResource",
    "isDefault": false
  },
  {
    "Label": "Types & Workflows",
    "Icon": "fa-solid fa-tags",
    "ResourceType": "Custom",
    "DriverClass": "IssueTypesSectionResource",
    "isDefault": false
  }
]'
SET
  @DefaultSequence_3bd750a6 = 100
SET
  @Status_3bd750a6 = N'Active'
SET
  @NavigationStyle_3bd750a6 = N'App Switcher'
SET
  @HideNavBarIconWhenActive_3bd750a6 = 0
SET
  @Path_3bd750a6 = N'issues'
SET
  @AutoUpdatePath_3bd750a6 = 1
EXEC [${mjSchema}].spCreateApplication @ID = @ID_3bd750a6,
  @Name = @Name_3bd750a6,
  @Description = @Description_3bd750a6,
  @Icon = @Icon_3bd750a6,
  @DefaultForNewUser = @DefaultForNewUser_3bd750a6,
  @SchemaAutoAddNewEntities = @SchemaAutoAddNewEntities_3bd750a6,
  @SchemaAutoAddNewEntities_Clear = 1,
  @Color = @Color_3bd750a6,
  @Color_Clear = 1,
  @DefaultNavItems = @DefaultNavItems_3bd750a6,
  @ClassName = @ClassName_3bd750a6,
  @ClassName_Clear = 1,
  @DefaultSequence = @DefaultSequence_3bd750a6,
  @Status = @Status_3bd750a6,
  @NavigationStyle = @NavigationStyle_3bd750a6,
  @TopNavLocation = @TopNavLocation_3bd750a6,
  @TopNavLocation_Clear = 1,
  @HideNavBarIconWhenActive = @HideNavBarIconWhenActive_3bd750a6,
  @Path = @Path_3bd750a6,
  @AutoUpdatePath = @AutoUpdatePath_3bd750a6,
  @AgentSettings = @AgentSettings_3bd750a6,
  @AgentSettings_Clear = 1;

GO

-- Save MJ: Entities (core SP call only)
DECLARE @ParentID_76a4cb62 UNIQUEIDENTIFIER,
@Name_76a4cb62 NVARCHAR(255),
@NameSuffix_76a4cb62 NVARCHAR(255),
@Description_76a4cb62 NVARCHAR(MAX),
@AutoUpdateDescription_76a4cb62 BIT,
@BaseView_76a4cb62 NVARCHAR(255),
@BaseViewGenerated_76a4cb62 BIT,
@VirtualEntity_76a4cb62 BIT,
@TrackRecordChanges_76a4cb62 BIT,
@AuditRecordAccess_76a4cb62 BIT,
@AuditViewRuns_76a4cb62 BIT,
@IncludeInAPI_76a4cb62 BIT,
@AllowAllRowsAPI_76a4cb62 BIT,
@AllowUpdateAPI_76a4cb62 BIT,
@AllowCreateAPI_76a4cb62 BIT,
@AllowDeleteAPI_76a4cb62 BIT,
@CustomResolverAPI_76a4cb62 BIT,
@AllowUserSearchAPI_76a4cb62 BIT,
@FullTextSearchEnabled_76a4cb62 BIT,
@FullTextCatalog_76a4cb62 NVARCHAR(255),
@FullTextCatalogGenerated_76a4cb62 BIT,
@FullTextIndex_76a4cb62 NVARCHAR(255),
@FullTextIndexGenerated_76a4cb62 BIT,
@FullTextSearchFunction_76a4cb62 NVARCHAR(255),
@FullTextSearchFunctionGenerated_76a4cb62 BIT,
@UserViewMaxRows_76a4cb62 INT,
@spCreate_76a4cb62 NVARCHAR(255),
@spUpdate_76a4cb62 NVARCHAR(255),
@spDelete_76a4cb62 NVARCHAR(255),
@spCreateGenerated_76a4cb62 BIT,
@spUpdateGenerated_76a4cb62 BIT,
@spDeleteGenerated_76a4cb62 BIT,
@CascadeDeletes_76a4cb62 BIT,
@DeleteType_76a4cb62 NVARCHAR(10),
@AllowRecordMerge_76a4cb62 BIT,
@spMatch_76a4cb62 NVARCHAR(255),
@RelationshipDefaultDisplayType_76a4cb62 NVARCHAR(20),
@UserFormGenerated_76a4cb62 BIT,
@EntityObjectSubclassName_76a4cb62 NVARCHAR(255),
@EntityObjectSubclassImport_76a4cb62 NVARCHAR(255),
@PreferredCommunicationField_76a4cb62 NVARCHAR(255),
@Icon_76a4cb62 NVARCHAR(500),
@ScopeDefault_76a4cb62 NVARCHAR(100),
@RowsToPackWithSchema_76a4cb62 NVARCHAR(20),
@RowsToPackSampleMethod_76a4cb62 NVARCHAR(20),
@RowsToPackSampleCount_76a4cb62 INT,
@RowsToPackSampleOrder_76a4cb62 NVARCHAR(MAX),
@AutoRowCountFrequency_76a4cb62 INT,
@RowCount_76a4cb62 BIGINT,
@RowCountRunAt_76a4cb62 DATETIMEOFFSET,
@Status_76a4cb62 NVARCHAR(25),
@DisplayName_76a4cb62 NVARCHAR(255),
@AllowMultipleSubtypes_76a4cb62 BIT,
@AutoUpdateFullTextSearch_76a4cb62 BIT,
@AutoUpdateAllowUserSearchAPI_76a4cb62 BIT,
@TrustServerCacheCompletely_76a4cb62 BIT,
@SupportsGeoCoding_76a4cb62 BIT,
@AutoUpdateSupportsGeoCoding_76a4cb62 BIT,
@AllowCaching_76a4cb62 BIT,
@DetectExternalChanges_76a4cb62 BIT,
@ExternalDataSourceID_76a4cb62 UNIQUEIDENTIFIER,
@ExternalObjectName_76a4cb62 NVARCHAR(255),
@GeneratedBaseViewName_76a4cb62 NVARCHAR(255),
@AllowDirectSQLInsert_76a4cb62 BIT,
@AllowDirectSQLUpdate_76a4cb62 BIT,
@AllowDirectSQLDelete_76a4cb62 BIT,
@Configuration_76a4cb62 NVARCHAR(MAX),
@ID_76a4cb62 UNIQUEIDENTIFIER
SET
  @Name_76a4cb62 = N'MJ_BizApps_Issues: Issues'
SET
  @Description_76a4cb62 = N'The core case / ticket / feedback record. Carries reporter, polymorphic assignee (Person or AI Agent), and a polymorphic source (any record the issue is about). Spawns bizapps-tasks Tasks for the actual work via TaskLink.'
SET
  @AutoUpdateDescription_76a4cb62 = 1
SET
  @BaseView_76a4cb62 = N'vwIssues'
SET
  @BaseViewGenerated_76a4cb62 = 1
SET
  @VirtualEntity_76a4cb62 = 0
SET
  @TrackRecordChanges_76a4cb62 = 1
SET
  @AuditRecordAccess_76a4cb62 = 0
SET
  @AuditViewRuns_76a4cb62 = 0
SET
  @IncludeInAPI_76a4cb62 = 1
SET
  @AllowAllRowsAPI_76a4cb62 = 0
SET
  @AllowUpdateAPI_76a4cb62 = 1
SET
  @AllowCreateAPI_76a4cb62 = 1
SET
  @AllowDeleteAPI_76a4cb62 = 1
SET
  @CustomResolverAPI_76a4cb62 = 0
SET
  @AllowUserSearchAPI_76a4cb62 = 1
SET
  @FullTextSearchEnabled_76a4cb62 = 0
SET
  @FullTextCatalogGenerated_76a4cb62 = 1
SET
  @FullTextIndexGenerated_76a4cb62 = 1
SET
  @FullTextSearchFunctionGenerated_76a4cb62 = 1
SET
  @UserViewMaxRows_76a4cb62 = 1000
SET
  @spCreateGenerated_76a4cb62 = 1
SET
  @spUpdateGenerated_76a4cb62 = 1
SET
  @spDeleteGenerated_76a4cb62 = 1
SET
  @CascadeDeletes_76a4cb62 = 0
SET
  @DeleteType_76a4cb62 = N'Hard'
SET
  @AllowRecordMerge_76a4cb62 = 0
SET
  @RelationshipDefaultDisplayType_76a4cb62 = N'Search'
SET
  @UserFormGenerated_76a4cb62 = 1
SET
  @RowsToPackWithSchema_76a4cb62 = N'None'
SET
  @RowsToPackSampleMethod_76a4cb62 = N'random'
SET
  @RowsToPackSampleCount_76a4cb62 = 0
SET
  @Status_76a4cb62 = N'Active'
SET
  @DisplayName_76a4cb62 = N'Issues'
SET
  @AllowMultipleSubtypes_76a4cb62 = 0
SET
  @AutoUpdateFullTextSearch_76a4cb62 = 1
SET
  @AutoUpdateAllowUserSearchAPI_76a4cb62 = 1
SET
  @TrustServerCacheCompletely_76a4cb62 = 1
SET
  @SupportsGeoCoding_76a4cb62 = 0
SET
  @AutoUpdateSupportsGeoCoding_76a4cb62 = 1
SET
  @AllowCaching_76a4cb62 = 0
SET
  @DetectExternalChanges_76a4cb62 = 0
SET
  @AllowDirectSQLInsert_76a4cb62 = 0
SET
  @AllowDirectSQLUpdate_76a4cb62 = 0
SET
  @AllowDirectSQLDelete_76a4cb62 = 0
SET
  @Configuration_76a4cb62 = N'{
  "UI": {
    "Form": {
      "Layout": "left-nav",
      "RelatedRolePolicy": "smart",
      "PrimaryRelatedBudget": 6
    }
  }
}'
SET
  @ID_76a4cb62 = '65E7DAD5-9930-4140-9A38-2184EB0097DA' EXEC [${mjSchema}].spUpdateEntity @ParentID = @ParentID_76a4cb62,
  @ParentID_Clear = 1,
  @Name = @Name_76a4cb62,
  @NameSuffix = @NameSuffix_76a4cb62,
  @NameSuffix_Clear = 1,
  @Description = @Description_76a4cb62,
  @AutoUpdateDescription = @AutoUpdateDescription_76a4cb62,
  @BaseView = @BaseView_76a4cb62,
  @BaseViewGenerated = @BaseViewGenerated_76a4cb62,
  @VirtualEntity = @VirtualEntity_76a4cb62,
  @TrackRecordChanges = @TrackRecordChanges_76a4cb62,
  @AuditRecordAccess = @AuditRecordAccess_76a4cb62,
  @AuditViewRuns = @AuditViewRuns_76a4cb62,
  @IncludeInAPI = @IncludeInAPI_76a4cb62,
  @AllowAllRowsAPI = @AllowAllRowsAPI_76a4cb62,
  @AllowUpdateAPI = @AllowUpdateAPI_76a4cb62,
  @AllowCreateAPI = @AllowCreateAPI_76a4cb62,
  @AllowDeleteAPI = @AllowDeleteAPI_76a4cb62,
  @CustomResolverAPI = @CustomResolverAPI_76a4cb62,
  @AllowUserSearchAPI = @AllowUserSearchAPI_76a4cb62,
  @FullTextSearchEnabled = @FullTextSearchEnabled_76a4cb62,
  @FullTextCatalog = @FullTextCatalog_76a4cb62,
  @FullTextCatalog_Clear = 1,
  @FullTextCatalogGenerated = @FullTextCatalogGenerated_76a4cb62,
  @FullTextIndex = @FullTextIndex_76a4cb62,
  @FullTextIndex_Clear = 1,
  @FullTextIndexGenerated = @FullTextIndexGenerated_76a4cb62,
  @FullTextSearchFunction = @FullTextSearchFunction_76a4cb62,
  @FullTextSearchFunction_Clear = 1,
  @FullTextSearchFunctionGenerated = @FullTextSearchFunctionGenerated_76a4cb62,
  @UserViewMaxRows = @UserViewMaxRows_76a4cb62,
  @spCreate = @spCreate_76a4cb62,
  @spCreate_Clear = 1,
  @spUpdate = @spUpdate_76a4cb62,
  @spUpdate_Clear = 1,
  @spDelete = @spDelete_76a4cb62,
  @spDelete_Clear = 1,
  @spCreateGenerated = @spCreateGenerated_76a4cb62,
  @spUpdateGenerated = @spUpdateGenerated_76a4cb62,
  @spDeleteGenerated = @spDeleteGenerated_76a4cb62,
  @CascadeDeletes = @CascadeDeletes_76a4cb62,
  @DeleteType = @DeleteType_76a4cb62,
  @AllowRecordMerge = @AllowRecordMerge_76a4cb62,
  @spMatch = @spMatch_76a4cb62,
  @spMatch_Clear = 1,
  @RelationshipDefaultDisplayType = @RelationshipDefaultDisplayType_76a4cb62,
  @UserFormGenerated = @UserFormGenerated_76a4cb62,
  @EntityObjectSubclassName = @EntityObjectSubclassName_76a4cb62,
  @EntityObjectSubclassName_Clear = 1,
  @EntityObjectSubclassImport = @EntityObjectSubclassImport_76a4cb62,
  @EntityObjectSubclassImport_Clear = 1,
  @PreferredCommunicationField = @PreferredCommunicationField_76a4cb62,
  @PreferredCommunicationField_Clear = 1,
  @Icon = @Icon_76a4cb62,
  @Icon_Clear = 1,
  @ScopeDefault = @ScopeDefault_76a4cb62,
  @ScopeDefault_Clear = 1,
  @RowsToPackWithSchema = @RowsToPackWithSchema_76a4cb62,
  @RowsToPackSampleMethod = @RowsToPackSampleMethod_76a4cb62,
  @RowsToPackSampleCount = @RowsToPackSampleCount_76a4cb62,
  @RowsToPackSampleOrder = @RowsToPackSampleOrder_76a4cb62,
  @RowsToPackSampleOrder_Clear = 1,
  @AutoRowCountFrequency = @AutoRowCountFrequency_76a4cb62,
  @AutoRowCountFrequency_Clear = 1,
  @RowCount = @RowCount_76a4cb62,
  @RowCount_Clear = 1,
  @RowCountRunAt = @RowCountRunAt_76a4cb62,
  @RowCountRunAt_Clear = 1,
  @Status = @Status_76a4cb62,
  @DisplayName = @DisplayName_76a4cb62,
  @AllowMultipleSubtypes = @AllowMultipleSubtypes_76a4cb62,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_76a4cb62,
  @AutoUpdateAllowUserSearchAPI = @AutoUpdateAllowUserSearchAPI_76a4cb62,
  @TrustServerCacheCompletely = @TrustServerCacheCompletely_76a4cb62,
  @SupportsGeoCoding = @SupportsGeoCoding_76a4cb62,
  @AutoUpdateSupportsGeoCoding = @AutoUpdateSupportsGeoCoding_76a4cb62,
  @AllowCaching = @AllowCaching_76a4cb62,
  @DetectExternalChanges = @DetectExternalChanges_76a4cb62,
  @ExternalDataSourceID = @ExternalDataSourceID_76a4cb62,
  @ExternalDataSourceID_Clear = 1,
  @ExternalObjectName = @ExternalObjectName_76a4cb62,
  @ExternalObjectName_Clear = 1,
  @GeneratedBaseViewName = @GeneratedBaseViewName_76a4cb62,
  @GeneratedBaseViewName_Clear = 1,
  @AllowDirectSQLInsert = @AllowDirectSQLInsert_76a4cb62,
  @AllowDirectSQLUpdate = @AllowDirectSQLUpdate_76a4cb62,
  @AllowDirectSQLDelete = @AllowDirectSQLDelete_76a4cb62,
  @Configuration = @Configuration_76a4cb62,
  @ID = @ID_76a4cb62;

GO

-- Save MJ: Entity Relationships (core SP call only)
DECLARE @EntityID_fea32969 UNIQUEIDENTIFIER,
@Sequence_fea32969 INT,
@RelatedEntityID_fea32969 UNIQUEIDENTIFIER,
@BundleInAPI_fea32969 BIT,
@IncludeInParentAllQuery_fea32969 BIT,
@Type_fea32969 NCHAR(20),
@EntityKeyField_fea32969 NVARCHAR(255),
@RelatedEntityJoinField_fea32969 NVARCHAR(255),
@JoinView_fea32969 NVARCHAR(255),
@JoinEntityJoinField_fea32969 NVARCHAR(255),
@JoinEntityInverseJoinField_fea32969 NVARCHAR(255),
@DisplayInForm_fea32969 BIT,
@DisplayLocation_fea32969 NVARCHAR(50),
@DisplayName_fea32969 NVARCHAR(255),
@DisplayIconType_fea32969 NVARCHAR(50),
@DisplayIcon_fea32969 NVARCHAR(255),
@DisplayComponentID_fea32969 UNIQUEIDENTIFIER,
@DisplayComponentConfiguration_fea32969 NVARCHAR(MAX),
@AutoUpdateFromSchema_fea32969 BIT,
@AdditionalFieldsToInclude_fea32969 NVARCHAR(MAX),
@AutoUpdateAdditionalFieldsToInclude_fea32969 BIT,
@RelatedRecordCollection_fea32969 NVARCHAR(MAX),
@Configuration_fea32969 NVARCHAR(MAX),
@ID_fea32969 UNIQUEIDENTIFIER
SET
  @EntityID_fea32969 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @Sequence_fea32969 = 9
SET
  @RelatedEntityID_fea32969 = '65E7DAD5-9930-4140-9A38-2184EB0097DA'
SET
  @BundleInAPI_fea32969 = 1
SET
  @IncludeInParentAllQuery_fea32969 = 0
SET
  @Type_fea32969 = N'One To Many'
SET
  @RelatedEntityJoinField_fea32969 = N'ReporterPersonID'
SET
  @DisplayInForm_fea32969 = 1
SET
  @DisplayLocation_fea32969 = N'After Field Tabs'
SET
  @DisplayIconType_fea32969 = N'Related Entity Icon'
SET
  @AutoUpdateFromSchema_fea32969 = 1
SET
  @AutoUpdateAdditionalFieldsToInclude_fea32969 = 1
SET
  @Configuration_fea32969 = N'{
  "UI": {
    "inclusion": "Primary"
  }
}'
SET
  @ID_fea32969 = '1CE94364-82A1-44EF-8FEB-0F8785691AB4' EXEC [${mjSchema}].spUpdateEntityRelationship @EntityID = @EntityID_fea32969,
  @Sequence = @Sequence_fea32969,
  @RelatedEntityID = @RelatedEntityID_fea32969,
  @BundleInAPI = @BundleInAPI_fea32969,
  @IncludeInParentAllQuery = @IncludeInParentAllQuery_fea32969,
  @Type = @Type_fea32969,
  @EntityKeyField = @EntityKeyField_fea32969,
  @EntityKeyField_Clear = 1,
  @RelatedEntityJoinField = @RelatedEntityJoinField_fea32969,
  @JoinView = @JoinView_fea32969,
  @JoinView_Clear = 1,
  @JoinEntityJoinField = @JoinEntityJoinField_fea32969,
  @JoinEntityJoinField_Clear = 1,
  @JoinEntityInverseJoinField = @JoinEntityInverseJoinField_fea32969,
  @JoinEntityInverseJoinField_Clear = 1,
  @DisplayInForm = @DisplayInForm_fea32969,
  @DisplayLocation = @DisplayLocation_fea32969,
  @DisplayName = @DisplayName_fea32969,
  @DisplayName_Clear = 1,
  @DisplayIconType = @DisplayIconType_fea32969,
  @DisplayIcon = @DisplayIcon_fea32969,
  @DisplayIcon_Clear = 1,
  @DisplayComponentID = @DisplayComponentID_fea32969,
  @DisplayComponentID_Clear = 1,
  @DisplayComponentConfiguration = @DisplayComponentConfiguration_fea32969,
  @DisplayComponentConfiguration_Clear = 1,
  @AutoUpdateFromSchema = @AutoUpdateFromSchema_fea32969,
  @AdditionalFieldsToInclude = @AdditionalFieldsToInclude_fea32969,
  @AdditionalFieldsToInclude_Clear = 1,
  @AutoUpdateAdditionalFieldsToInclude = @AutoUpdateAdditionalFieldsToInclude_fea32969,
  @RelatedRecordCollection = @RelatedRecordCollection_fea32969,
  @RelatedRecordCollection_Clear = 1,
  @Configuration = @Configuration_fea32969,
  @ID = @ID_fea32969;

GO

-- Save MJ: Entity Relationships (core SP call only)
DECLARE @EntityID_6b06e287 UNIQUEIDENTIFIER,
@Sequence_6b06e287 INT,
@RelatedEntityID_6b06e287 UNIQUEIDENTIFIER,
@BundleInAPI_6b06e287 BIT,
@IncludeInParentAllQuery_6b06e287 BIT,
@Type_6b06e287 NCHAR(20),
@EntityKeyField_6b06e287 NVARCHAR(255),
@RelatedEntityJoinField_6b06e287 NVARCHAR(255),
@JoinView_6b06e287 NVARCHAR(255),
@JoinEntityJoinField_6b06e287 NVARCHAR(255),
@JoinEntityInverseJoinField_6b06e287 NVARCHAR(255),
@DisplayInForm_6b06e287 BIT,
@DisplayLocation_6b06e287 NVARCHAR(50),
@DisplayName_6b06e287 NVARCHAR(255),
@DisplayIconType_6b06e287 NVARCHAR(50),
@DisplayIcon_6b06e287 NVARCHAR(255),
@DisplayComponentID_6b06e287 UNIQUEIDENTIFIER,
@DisplayComponentConfiguration_6b06e287 NVARCHAR(MAX),
@AutoUpdateFromSchema_6b06e287 BIT,
@AdditionalFieldsToInclude_6b06e287 NVARCHAR(MAX),
@AutoUpdateAdditionalFieldsToInclude_6b06e287 BIT,
@RelatedRecordCollection_6b06e287 NVARCHAR(MAX),
@Configuration_6b06e287 NVARCHAR(MAX),
@ID_6b06e287 UNIQUEIDENTIFIER
SET
  @EntityID_6b06e287 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @Sequence_6b06e287 = 8
SET
  @RelatedEntityID_6b06e287 = '7124A46D-EA35-4C8B-BBBB-F19287ED0F9B'
SET
  @BundleInAPI_6b06e287 = 1
SET
  @IncludeInParentAllQuery_6b06e287 = 0
SET
  @Type_6b06e287 = N'One To Many'
SET
  @RelatedEntityJoinField_6b06e287 = N'AuthorPersonID'
SET
  @DisplayInForm_6b06e287 = 1
SET
  @DisplayLocation_6b06e287 = N'After Field Tabs'
SET
  @DisplayIconType_6b06e287 = N'Related Entity Icon'
SET
  @AutoUpdateFromSchema_6b06e287 = 1
SET
  @AutoUpdateAdditionalFieldsToInclude_6b06e287 = 1
SET
  @Configuration_6b06e287 = N'{
  "UI": {
    "inclusion": "None"
  }
}'
SET
  @ID_6b06e287 = '2C0B564A-D076-4591-9687-F62FEFBB3F75' EXEC [${mjSchema}].spUpdateEntityRelationship @EntityID = @EntityID_6b06e287,
  @Sequence = @Sequence_6b06e287,
  @RelatedEntityID = @RelatedEntityID_6b06e287,
  @BundleInAPI = @BundleInAPI_6b06e287,
  @IncludeInParentAllQuery = @IncludeInParentAllQuery_6b06e287,
  @Type = @Type_6b06e287,
  @EntityKeyField = @EntityKeyField_6b06e287,
  @EntityKeyField_Clear = 1,
  @RelatedEntityJoinField = @RelatedEntityJoinField_6b06e287,
  @JoinView = @JoinView_6b06e287,
  @JoinView_Clear = 1,
  @JoinEntityJoinField = @JoinEntityJoinField_6b06e287,
  @JoinEntityJoinField_Clear = 1,
  @JoinEntityInverseJoinField = @JoinEntityInverseJoinField_6b06e287,
  @JoinEntityInverseJoinField_Clear = 1,
  @DisplayInForm = @DisplayInForm_6b06e287,
  @DisplayLocation = @DisplayLocation_6b06e287,
  @DisplayName = @DisplayName_6b06e287,
  @DisplayName_Clear = 1,
  @DisplayIconType = @DisplayIconType_6b06e287,
  @DisplayIcon = @DisplayIcon_6b06e287,
  @DisplayIcon_Clear = 1,
  @DisplayComponentID = @DisplayComponentID_6b06e287,
  @DisplayComponentID_Clear = 1,
  @DisplayComponentConfiguration = @DisplayComponentConfiguration_6b06e287,
  @DisplayComponentConfiguration_Clear = 1,
  @AutoUpdateFromSchema = @AutoUpdateFromSchema_6b06e287,
  @AdditionalFieldsToInclude = @AdditionalFieldsToInclude_6b06e287,
  @AdditionalFieldsToInclude_Clear = 1,
  @AutoUpdateAdditionalFieldsToInclude = @AutoUpdateAdditionalFieldsToInclude_6b06e287,
  @RelatedRecordCollection = @RelatedRecordCollection_6b06e287,
  @RelatedRecordCollection_Clear = 1,
  @Configuration = @Configuration_6b06e287,
  @ID = @ID_6b06e287;

GO

-- Save MJ: Entity Relationships (core SP call only)
DECLARE @EntityID_ddabfe21 UNIQUEIDENTIFIER,
@Sequence_ddabfe21 INT,
@RelatedEntityID_ddabfe21 UNIQUEIDENTIFIER,
@BundleInAPI_ddabfe21 BIT,
@IncludeInParentAllQuery_ddabfe21 BIT,
@Type_ddabfe21 NCHAR(20),
@EntityKeyField_ddabfe21 NVARCHAR(255),
@RelatedEntityJoinField_ddabfe21 NVARCHAR(255),
@JoinView_ddabfe21 NVARCHAR(255),
@JoinEntityJoinField_ddabfe21 NVARCHAR(255),
@JoinEntityInverseJoinField_ddabfe21 NVARCHAR(255),
@DisplayInForm_ddabfe21 BIT,
@DisplayLocation_ddabfe21 NVARCHAR(50),
@DisplayName_ddabfe21 NVARCHAR(255),
@DisplayIconType_ddabfe21 NVARCHAR(50),
@DisplayIcon_ddabfe21 NVARCHAR(255),
@DisplayComponentID_ddabfe21 UNIQUEIDENTIFIER,
@DisplayComponentConfiguration_ddabfe21 NVARCHAR(MAX),
@AutoUpdateFromSchema_ddabfe21 BIT,
@AdditionalFieldsToInclude_ddabfe21 NVARCHAR(MAX),
@AutoUpdateAdditionalFieldsToInclude_ddabfe21 BIT,
@RelatedRecordCollection_ddabfe21 NVARCHAR(MAX),
@Configuration_ddabfe21 NVARCHAR(MAX),
@ID_ddabfe21 UNIQUEIDENTIFIER
SET
  @EntityID_ddabfe21 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @Sequence_ddabfe21 = 10
SET
  @RelatedEntityID_ddabfe21 = '65E7DAD5-9930-4140-9A38-2184EB0097DA'
SET
  @BundleInAPI_ddabfe21 = 1
SET
  @IncludeInParentAllQuery_ddabfe21 = 0
SET
  @Type_ddabfe21 = N'One To Many'
SET
  @RelatedEntityJoinField_ddabfe21 = N'CreatedByPersonID'
SET
  @DisplayInForm_ddabfe21 = 1
SET
  @DisplayLocation_ddabfe21 = N'After Field Tabs'
SET
  @DisplayIconType_ddabfe21 = N'Related Entity Icon'
SET
  @AutoUpdateFromSchema_ddabfe21 = 1
SET
  @AutoUpdateAdditionalFieldsToInclude_ddabfe21 = 1
SET
  @Configuration_ddabfe21 = N'{
  "UI": {
    "inclusion": "None"
  }
}'
SET
  @ID_ddabfe21 = '50190ACD-091E-41D6-8738-AEABCC020DDB' EXEC [${mjSchema}].spUpdateEntityRelationship @EntityID = @EntityID_ddabfe21,
  @Sequence = @Sequence_ddabfe21,
  @RelatedEntityID = @RelatedEntityID_ddabfe21,
  @BundleInAPI = @BundleInAPI_ddabfe21,
  @IncludeInParentAllQuery = @IncludeInParentAllQuery_ddabfe21,
  @Type = @Type_ddabfe21,
  @EntityKeyField = @EntityKeyField_ddabfe21,
  @EntityKeyField_Clear = 1,
  @RelatedEntityJoinField = @RelatedEntityJoinField_ddabfe21,
  @JoinView = @JoinView_ddabfe21,
  @JoinView_Clear = 1,
  @JoinEntityJoinField = @JoinEntityJoinField_ddabfe21,
  @JoinEntityJoinField_Clear = 1,
  @JoinEntityInverseJoinField = @JoinEntityInverseJoinField_ddabfe21,
  @JoinEntityInverseJoinField_Clear = 1,
  @DisplayInForm = @DisplayInForm_ddabfe21,
  @DisplayLocation = @DisplayLocation_ddabfe21,
  @DisplayName = @DisplayName_ddabfe21,
  @DisplayName_Clear = 1,
  @DisplayIconType = @DisplayIconType_ddabfe21,
  @DisplayIcon = @DisplayIcon_ddabfe21,
  @DisplayIcon_Clear = 1,
  @DisplayComponentID = @DisplayComponentID_ddabfe21,
  @DisplayComponentID_Clear = 1,
  @DisplayComponentConfiguration = @DisplayComponentConfiguration_ddabfe21,
  @DisplayComponentConfiguration_Clear = 1,
  @AutoUpdateFromSchema = @AutoUpdateFromSchema_ddabfe21,
  @AdditionalFieldsToInclude = @AdditionalFieldsToInclude_ddabfe21,
  @AdditionalFieldsToInclude_Clear = 1,
  @AutoUpdateAdditionalFieldsToInclude = @AutoUpdateAdditionalFieldsToInclude_ddabfe21,
  @RelatedRecordCollection = @RelatedRecordCollection_ddabfe21,
  @RelatedRecordCollection_Clear = 1,
  @Configuration = @Configuration_ddabfe21,
  @ID = @ID_ddabfe21;

GO

-- Save MJ: Entity Relationships (core SP call only)
DECLARE @EntityID_9fa057ca UNIQUEIDENTIFIER,
@Sequence_9fa057ca INT,
@RelatedEntityID_9fa057ca UNIQUEIDENTIFIER,
@BundleInAPI_9fa057ca BIT,
@IncludeInParentAllQuery_9fa057ca BIT,
@Type_9fa057ca NCHAR(20),
@EntityKeyField_9fa057ca NVARCHAR(255),
@RelatedEntityJoinField_9fa057ca NVARCHAR(255),
@JoinView_9fa057ca NVARCHAR(255),
@JoinEntityJoinField_9fa057ca NVARCHAR(255),
@JoinEntityInverseJoinField_9fa057ca NVARCHAR(255),
@DisplayInForm_9fa057ca BIT,
@DisplayLocation_9fa057ca NVARCHAR(50),
@DisplayName_9fa057ca NVARCHAR(255),
@DisplayIconType_9fa057ca NVARCHAR(50),
@DisplayIcon_9fa057ca NVARCHAR(255),
@DisplayComponentID_9fa057ca UNIQUEIDENTIFIER,
@DisplayComponentConfiguration_9fa057ca NVARCHAR(MAX),
@AutoUpdateFromSchema_9fa057ca BIT,
@AdditionalFieldsToInclude_9fa057ca NVARCHAR(MAX),
@AutoUpdateAdditionalFieldsToInclude_9fa057ca BIT,
@RelatedRecordCollection_9fa057ca NVARCHAR(MAX),
@Configuration_9fa057ca NVARCHAR(MAX),
@ID_9fa057ca UNIQUEIDENTIFIER
SET
  @EntityID_9fa057ca = '65E7DAD5-9930-4140-9A38-2184EB0097DA'
SET
  @Sequence_9fa057ca = 1
SET
  @RelatedEntityID_9fa057ca = '7124A46D-EA35-4C8B-BBBB-F19287ED0F9B'
SET
  @BundleInAPI_9fa057ca = 1
SET
  @IncludeInParentAllQuery_9fa057ca = 0
SET
  @Type_9fa057ca = N'One To Many'
SET
  @RelatedEntityJoinField_9fa057ca = N'IssueID'
SET
  @DisplayInForm_9fa057ca = 1
SET
  @DisplayLocation_9fa057ca = N'After Field Tabs'
SET
  @DisplayIconType_9fa057ca = N'Related Entity Icon'
SET
  @AutoUpdateFromSchema_9fa057ca = 1
SET
  @AutoUpdateAdditionalFieldsToInclude_9fa057ca = 1
SET
  @Configuration_9fa057ca = N'{
  "UI": {
    "inclusion": "Primary"
  }
}'
SET
  @ID_9fa057ca = 'CAE6EB89-1CB9-4391-81D9-124BBAC74644' EXEC [${mjSchema}].spUpdateEntityRelationship @EntityID = @EntityID_9fa057ca,
  @Sequence = @Sequence_9fa057ca,
  @RelatedEntityID = @RelatedEntityID_9fa057ca,
  @BundleInAPI = @BundleInAPI_9fa057ca,
  @IncludeInParentAllQuery = @IncludeInParentAllQuery_9fa057ca,
  @Type = @Type_9fa057ca,
  @EntityKeyField = @EntityKeyField_9fa057ca,
  @EntityKeyField_Clear = 1,
  @RelatedEntityJoinField = @RelatedEntityJoinField_9fa057ca,
  @JoinView = @JoinView_9fa057ca,
  @JoinView_Clear = 1,
  @JoinEntityJoinField = @JoinEntityJoinField_9fa057ca,
  @JoinEntityJoinField_Clear = 1,
  @JoinEntityInverseJoinField = @JoinEntityInverseJoinField_9fa057ca,
  @JoinEntityInverseJoinField_Clear = 1,
  @DisplayInForm = @DisplayInForm_9fa057ca,
  @DisplayLocation = @DisplayLocation_9fa057ca,
  @DisplayName = @DisplayName_9fa057ca,
  @DisplayName_Clear = 1,
  @DisplayIconType = @DisplayIconType_9fa057ca,
  @DisplayIcon = @DisplayIcon_9fa057ca,
  @DisplayIcon_Clear = 1,
  @DisplayComponentID = @DisplayComponentID_9fa057ca,
  @DisplayComponentID_Clear = 1,
  @DisplayComponentConfiguration = @DisplayComponentConfiguration_9fa057ca,
  @DisplayComponentConfiguration_Clear = 1,
  @AutoUpdateFromSchema = @AutoUpdateFromSchema_9fa057ca,
  @AdditionalFieldsToInclude = @AdditionalFieldsToInclude_9fa057ca,
  @AdditionalFieldsToInclude_Clear = 1,
  @AutoUpdateAdditionalFieldsToInclude = @AutoUpdateAdditionalFieldsToInclude_9fa057ca,
  @RelatedRecordCollection = @RelatedRecordCollection_9fa057ca,
  @RelatedRecordCollection_Clear = 1,
  @Configuration = @Configuration_9fa057ca,
  @ID = @ID_9fa057ca;

GO

-- Save MJ: Application Roles (core SP call only)
DECLARE @ID_46a56431 UNIQUEIDENTIFIER,
@ApplicationID_46a56431 UNIQUEIDENTIFIER,
@RoleID_46a56431 UNIQUEIDENTIFIER,
@CanAccess_46a56431 BIT,
@CanAdmin_46a56431 BIT
SET
  @ID_46a56431 = 'E91C281F-A60A-4E1B-9477-9E49B74F3AA1'
SET
  @ApplicationID_46a56431 = '1D63E8A6-BFFA-4EA7-8231-7565CABBE53E'
SET
  @RoleID_46a56431 = 'E0AFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @CanAccess_46a56431 = 1
SET
  @CanAdmin_46a56431 = 0
EXEC [${mjSchema}].spCreateApplicationRole @ID = @ID_46a56431,
  @ApplicationID = @ApplicationID_46a56431,
  @RoleID = @RoleID_46a56431,
  @CanAccess = @CanAccess_46a56431,
  @CanAdmin = @CanAdmin_46a56431;

GO

-- Save MJ: Application Roles (core SP call only)
DECLARE @ID_d84f59e1 UNIQUEIDENTIFIER,
@ApplicationID_d84f59e1 UNIQUEIDENTIFIER,
@RoleID_d84f59e1 UNIQUEIDENTIFIER,
@CanAccess_d84f59e1 BIT,
@CanAdmin_d84f59e1 BIT
SET
  @ID_d84f59e1 = 'F02D392E-B71B-4F2C-A588-AF50C85E4BB2'
SET
  @ApplicationID_d84f59e1 = '1D63E8A6-BFFA-4EA7-8231-7565CABBE53E'
SET
  @RoleID_d84f59e1 = 'DEAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @CanAccess_d84f59e1 = 1
SET
  @CanAdmin_d84f59e1 = 1
EXEC [${mjSchema}].spCreateApplicationRole @ID = @ID_d84f59e1,
  @ApplicationID = @ApplicationID_d84f59e1,
  @RoleID = @RoleID_d84f59e1,
  @CanAccess = @CanAccess_d84f59e1,
  @CanAdmin = @CanAdmin_d84f59e1;

GO


-- End of SQL Logging Session
-- Session ID: 211e31ed-33e2-46d2-9693-a6bbabdc00e1
-- Completed: 2026-08-27T18:39:20.713Z
-- Duration: 1440ms
-- Total Statements: 10
