-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj_bizappsissues;
SET search_path TO __mj_bizappsissues, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- NOTE: Earlier converter versions made INTEGER to BOOLEAN cast implicit by
-- modifying the system catalog so SS-style INSERT INTO bool_col VALUES (1)
-- would work. That modification required pg_catalog write privileges, which
-- managed PG (RDS, Aurora, Cloud SQL, Azure) does not grant. As of v5.30 all
-- bulk INSERTs are emitted with native TRUE/FALSE values directly, so the
-- cast modification is no longer needed. Removed to support managed-PG
-- installs out of the box.


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- SQL Logging Session
-- Session ID: 480353f5-27ce-4770-b09e-5dcb1d13cb12
-- Started: 2026-06-23T02:19:20.112Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- NOTE: The converter emitted these seed blocks as PERFORM
-- __mj_bizappsissues."spCreateIssueStatus"/"spCreateIssueType" calls. Those
-- CRUD functions cannot exist at migration time on PostgreSQL — they are
-- created by `mj codegen` AFTER install — so the blocks are replaced with
-- idempotent direct INSERTs (same IDs and values as the SQL Server twin).
-- Future PG metadata-sync migrations must author seed data as plain INSERTs.

-- Save MJ_BizApps_Issues: Issue Status (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueStatus" ("ID", "Name", "Description", "Sequence", "IsDefault", "IsTerminal", "ColorCode", "IsResolved")
VALUES ('E02A9B9E-45A0-4853-A82C-EDDC00BA5126', 'New', 'Newly reported, not yet triaged.', 10, TRUE, FALSE, '#EAB308', FALSE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Status (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueStatus" ("ID", "Name", "Description", "Sequence", "IsDefault", "IsTerminal", "ColorCode", "IsResolved")
VALUES ('6C38314F-970D-4965-9D9E-48D6BBF690A0', 'Triaged', 'Reviewed and accepted; prioritized and ready to be worked.', 20, FALSE, FALSE, '#8B5CF6', FALSE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Status (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueStatus" ("ID", "Name", "Description", "Sequence", "IsDefault", "IsTerminal", "ColorCode", "IsResolved")
VALUES ('4A9D16B2-3CFC-4E4A-A94E-B1C0D0CBFA1D', 'In Progress', 'Actively being worked on.', 30, FALSE, FALSE, '#3B82F6', FALSE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Status (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueStatus" ("ID", "Name", "Description", "Sequence", "IsDefault", "IsTerminal", "ColorCode", "IsResolved")
VALUES ('20A6DDEC-24A3-4FAD-AF5B-F291B870255D', 'Waiting on Reporter', 'Blocked pending more information or a response from the reporter.', 40, FALSE, FALSE, '#F97316', FALSE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Status (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueStatus" ("ID", "Name", "Description", "Sequence", "IsDefault", "IsTerminal", "ColorCode", "IsResolved")
VALUES ('BA34155E-E6A5-4BAE-A57C-20BFF88275EA', 'Resolved', 'A fix or answer has been delivered; awaiting confirmation before closing.', 50, FALSE, FALSE, '#10B981', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Status (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueStatus" ("ID", "Name", "Description", "Sequence", "IsDefault", "IsTerminal", "ColorCode", "IsResolved")
VALUES ('DC42F011-C589-41BD-8FE0-D96258245E70', 'Closed', 'Completed and confirmed. Terminal state.', 60, FALSE, TRUE, '#475569', FALSE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Status (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueStatus" ("ID", "Name", "Description", "Sequence", "IsDefault", "IsTerminal", "ColorCode", "IsResolved")
VALUES ('7B4A372A-E9F9-4685-A093-9D69C3D892C2', 'Won''t Fix', 'Acknowledged but will not be addressed (by design, duplicate, or out of scope). Terminal state.', 70, FALSE, TRUE, '#9CA3AF', FALSE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('A4A4B67C-DEFF-4CA0-9F3C-2467CB2D2D8D', 'Bug', 'Something is broken or not behaving as intended.', 'fa-solid fa-bug', 'High', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('34733CAF-A7C4-4AF1-A6B6-7F082192E53F', 'Feature Request', 'A request for new functionality or an enhancement.', 'fa-solid fa-lightbulb', 'Medium', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('5D6CE5C4-DFA7-452B-BDCD-0E5456C683B3', 'Question', 'A question or request for help; no code change necessarily implied.', 'fa-solid fa-circle-question', 'Low', TRUE)
ON CONFLICT ("ID") DO NOTHING;

-- Save MJ_BizApps_Issues: Issue Types (direct INSERT — on PG the CRUD functions are created later by CodeGen, so they do not exist at migration time)
INSERT INTO __mj_bizappsissues."IssueType" ("ID", "Name", "Description", "IconClass", "DefaultPriority", "IsActive")
VALUES ('FE0C6A23-ACF0-4826-BB07-1640767874C3', 'Feedback', 'General feedback or a suggestion, e.g. from the cloud feedback channel.', 'fa-solid fa-comment-dots', 'Medium', TRUE)
ON CONFLICT ("ID") DO NOTHING;


-- ===================== Other =====================

-- End of SQL Logging Session
-- Session ID: 480353f5-27ce-4770-b09e-5dcb1d13cb12
-- Completed: 2026-06-23T02:19:20.576Z
-- Duration: 464ms
-- Total Statements: 11
